Use luxon
concordnow/ember-pikaday pull request #1
Opened 2021-06-23 07:56 UTC by robinvrd

https://contractlive.atlassian.net/browse/CPM-12390

- `testdouble` has been removed & `ember-cli-babel` has been upgraded due to conflicts with webpack installation
- `Info.weekdays()` in Luxon is starting with `Monday` as it is ISO order
- Luxon format have changed a bit compared to momentjs

2021-06-23 12:20 UTC, ctjhoa requested changes

2021-06-23 12:20 UTC, ctjhoa commented on addon/mixins/pikaday.js
> +        selectedDate.getFullYear(),
Cette correction d'indentation devrait être dans le commit précédent

2021-06-23 12:20 UTC, ctjhoa commented on tests/dummy/app/initializers/setup-pikaday-i18n.js
> +    application.inject(
Pourquoi tu rajoutes ca ?

2021-06-23 12:20 UTC, ctjhoa commented on addon/mixins/pikaday.js
> +        DateTime.fromFormat(dateString, format).toJSDate(),
Pourquoi tu rajoutes ces 2 fonctions ?

2021-06-23 14:37 UTC, frykten commented on addon/mixins/pikaday.js
> +        DateTime.fromFormat(dateString, format).toJSDate(),
+1

2021-06-23 14:37 UTC, frykten commented on tests/dummy/app/initializers/setup-pikaday-i18n.js
> +    application.inject(
+1

2021-06-23 14:39 UTC, robinvrd commented on tests/dummy/app/initializers/setup-pikaday-i18n.js
> +    application.inject(
Les données `i18n` n'étaient pas ajoutées dans l'app dans le composant inputless (uniquement dans le composant input) ce qui n'avait pas trop de sens, je vais le sortir dans un autre commit :+1:

2021-06-23 14:40 UTC, robinvrd commented on addon/mixins/pikaday.js
> +        DateTime.fromFormat(dateString, format).toJSDate(),
`pikaday` sait travailler avec `momentjs` pour les formats, mais pas avec luxon, cependant il propose ces deux fonctions pour faire le formattage soit même, c'est grâce à ça que l'on peut utiliser le formattage de `luxon`.

2021-06-23 14:46 UTC, robinvrd commented on addon/mixins/pikaday.js
> +        selectedDate.getFullYear(),
https://github.com/concordnow/ember-pikaday/pull/1/commits/3bf86da435e7b1a8d098c50a1c69e4aba440b4bc réécrit :+1:

2021-06-23 14:49 UTC, robinvrd commented on tests/dummy/app/initializers/setup-pikaday-i18n.js
> +    application.inject(
https://github.com/concordnow/ember-pikaday/pull/1/commits/9f4153cfd3a226b19851a718f05ce5eaa2beec24

2021-06-23 14:50 UTC, robinvrd commented on addon/mixins/pikaday.js
> +        DateTime.fromFormat(dateString, format).toJSDate(),
https://github.com/Pikaday/Pikaday#formatting

2021-06-23 15:07 UTC, frykten approved these changes
La PR me paraît bonne.
Cependant, pour que le fork soit accepté, il faudra réécrire le README.md. C'est prévu plus tard ?

2021-06-23 15:26 UTC, ctjhoa approved these changes

2021-06-23 17:05 UTC, jonathanpruvost approved these changes

2021-06-24 07:10 UTC, KamiKillertO commented on addon/mixins/pikaday.js
> +            value.getUTCMonth() + 1,
Pourquoi le `+1` ?

2021-06-24 07:12 UTC, KamiKillertO commented on addon/mixins/pikaday.js
> +        selectedDate.getMonth() + 1,
Pourquoi le `+1`?

2021-06-24 07:14 UTC, KamiKillertO commented on tests/integration/components/pikaday-input-test.js
> +      <PikadayInput @firstDay={{6}}/>
Pourquoi changer 0 en 6 ?

2021-06-24 07:20 UTC, robinvrd commented on addon/mixins/pikaday.js
> +            value.getUTCMonth() + 1,
API Date Native : 0-indexed
Luxon : 1-indexed

2021-06-24 07:23 UTC, robinvrd commented on tests/integration/components/pikaday-input-test.js
> +      <PikadayInput @firstDay={{6}}/>
> Info.weekdays() in Luxon is starting with Monday as it is ISO order
Le test testait avec `Sunday`, et dans Luxon `[0] => Monday` et `[6] => Sunday`

2021-06-24 07:27 UTC, KamiKillertO approved these changes

2021-06-29 07:40 UTC, closed without merging